[tool.towncrier]
name = 'elbe'
package = 'elbepack'
directory = 'newsfragments'
single_file = false
filename = 'docs/news/{project_date}-v{version}.rst'

[tool.pytest.ini_options]
filterwarnings = 'error'

[tool.mypy]
packages = [
  'elbevalidate',
]
ignore_missing_imports = true
